// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl0TW2-2dyh4iaxN5lhJasIG4obsvpJXg',
    appId: '1:820141816276:web:5c99302f084755f5dcfe41',
    messagingSenderId: '820141816276',
    projectId: 'servicoestrega',
    authDomain: 'servicoestrega.firebaseapp.com',
    databaseURL: 'https://servicoestrega-default-rtdb.firebaseio.com',
    storageBucket: 'servicoestrega.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf700p6BKMgO6Q2X9UEuxXGn53g_1q974',
    appId: '1:820141816276:android:d04440910480057fdcfe41',
    messagingSenderId: '820141816276',
    projectId: 'servicoestrega',
    databaseURL: 'https://servicoestrega-default-rtdb.firebaseio.com',
    storageBucket: 'servicoestrega.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6onuxgetlKIJZOjt-w1Ugbnl4DaG4HvI',
    appId: '1:820141816276:ios:c2bac97991f38117dcfe41',
    messagingSenderId: '820141816276',
    projectId: 'servicoestrega',
    databaseURL: 'https://servicoestrega-default-rtdb.firebaseio.com',
    storageBucket: 'servicoestrega.appspot.com',
    iosBundleId: 'com.example.attPedidos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6onuxgetlKIJZOjt-w1Ugbnl4DaG4HvI',
    appId: '1:820141816276:ios:c2bac97991f38117dcfe41',
    messagingSenderId: '820141816276',
    projectId: 'servicoestrega',
    databaseURL: 'https://servicoestrega-default-rtdb.firebaseio.com',
    storageBucket: 'servicoestrega.appspot.com',
    iosBundleId: 'com.example.attPedidos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl0TW2-2dyh4iaxN5lhJasIG4obsvpJXg',
    appId: '1:820141816276:web:829ed54729180db2dcfe41',
    messagingSenderId: '820141816276',
    projectId: 'servicoestrega',
    authDomain: 'servicoestrega.firebaseapp.com',
    databaseURL: 'https://servicoestrega-default-rtdb.firebaseio.com',
    storageBucket: 'servicoestrega.appspot.com',
  );

}